vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /uploads/logo_sile
            upload_destination: '%kernel.project_dir%/public/uploads/logo_sile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#       attachment:
#           uri_prefix: /uploads/logo_sile/
#           upload_destination: '%kernel.project_dir%/public/uploads/logo_sile/'
